# Last modified at 2025/09/03 星期三 00:11:43
# TODO: READ hyperlink below.
# https://stibel.icu/devops/ci/local-repository.html
name: CI/CD validator designed for init.sh and clean_vimview.py

on: [push]
jobs:
  fetch-assets-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        payload: ["3\\n-1\\n1\\n1\\n", "3\\n-1\\n2\\n1\\n", "3\\n-1\\n1\\n2\\n", "3\\n-1\\n2\\n2\\n"]
      max-parallel: 2

    steps:
      - name: 切分支
        uses: actions/checkout@main
      - name: 安依赖
        run: sudo apt install bc coreutils cmake

      - name: 运行 init.sh 并检查是否安装得当
        env:
          payload: ${{ matrix.payload }}
        run: |
          set x
          sed -i 's/set -u/set -ux/g' init.sh
          echo -e "$payload" > tmp_inp.txt
          if [[ ! -s tmp_inp.txt ]]; then
            echo "invalid inp-file size was detected!"
            exit 1
          fi
          font_flag=`tail -n 1 tmp_inp.txt`
          bash init.sh < tmp_inp.txt
          bash init.sh < tmp_inp.txt && rm tmp_inp.txt
          cur_path=`pwd`
          cd "$HOME/.vim/" && ls autoload colors
          cd "$cur_path" && unset cur_path
          cat "$HOME/.vim/autoload/plug.vim" | grep -in "github.com"
          if [[ "$font_flag" != 1 ]]; then
            echo 'test pass...'
            exit 0
          fi
          ls "$HOME/.fonts/"
          [[ ! -s "$HOME/.config/fontconfig/fonts.conf" ]] && exit 1
          cat "$HOME/.config/fontconfig/fonts.conf" | grep -Ei "modified|lxgw|fira|jetbrains"

  mac-test:
    runs-on: macos-latest
    strategy:
      matrix:
        payload: ["3\\n-1\\n1\\n2\\n", "3\\n-1\\n2\\n2\\n"]
      max-parallel: 2
    steps:
      - name: setup-repo
        uses: actions/checkout@main
      - name: deps
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install wget grep gnu-sed perl vim python3
          gsed -i 's/set -u/set -ux/g' init.sh

      - name: task
        env:
          payload: ${{ matrix.payload }}
        run: |
          set -x
          echo -e "$payload" > tmp_inp.txt
          if [[ ! -s tmp_inp.txt ]]; then
            echo "invalid inp-file size was detected!"
            exit 1
          fi
          zsh init.sh < tmp_inp.txt

  python-remove-test:
    runs-on: ubuntu-latest
    steps:
      - name: 切分支
        uses: actions/checkout@main
      - name: 准备测试文件并测试
        run: |
          python --version
          test_files=(a b c d e f g)
          vimview="$HOME/.vim/view"
          mkdir -p "$vimview" && readlink -f "$vimview"
          for file in "${test_files[@]}"; do
            echo "123" > "$vimview/$file"
            touch -t 202001011145.14 "$vimview/$file"
          done
          ls "$vimview" && python clean_vimview.py && ls "$vimview"
          unset test_files vimview
