# Last modified at 2025年08月03日 星期日 01时17分06秒
# TODO: READ hyperlink below.
# https://stibel.icu/devops/ci/local-repository.html
name: CI/CD validator designed for init.sh, test.sh and clean_vimview.py

on: [push]
jobs:
  fetch-assets-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        payload: ["3\\n-1\\n1\\n","3\\n-1\\n2\\n"]
      max-parallel: 2

    steps:
      - name: 切分支
        uses: actions/checkout@main
      - name: 安依赖
        run: sudo apt install bc coreutils # libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev python3-dev ruby-dev lua5.1 liblua5.1-dev libperl-dev git

      - name: 运行 init.sh 并检查是否安装得当
        env:
          payload: ${{ matrix.payload }}
        run: |
          sed -i 's/set -u/set -ux/g' init.sh
          echo -e "$payload" > tmp_inp.txt
          if [[ ! -s tmp_inp.txt ]]; then
            echo "invalid inp-file size was detected!"
            exit 1
          fi
          bash init.sh < tmp_inp.txt && bash test.sh
          bash init.sh < tmp_inp.txt && rm tmp_inp.txt
          cur_path=`pwd`
          cd "$HOME/.vim/" && ls autoload colors "$HOME/.fonts/"
          cd "$cur_path" && unset cur_path
          cat "$HOME/.vim/autoload/plug.vim" | grep -in "github.com"
          [[ ! -s "$HOME/.config/fontconfig/fonts.conf" ]] && exit 1
          cat "$HOME/.config/fontconfig/fonts.conf" | grep -Ei "modified|lxgw|fira|jetbrains"

  python-remove-test:
    runs-on: ubuntu-latest
    steps:
      - name: 切分支
        uses: actions/checkout@main
        # python in ubuntu-latest 3.12.3
      - name: 准备测试文件并测试
        run: |
          python --version
          test_files=(a b c d e f g)
          vimview="$HOME/.vim/view"
          mkdir -p "$vimview" && readlink -f "$vimview"
          for file in "${test_files[@]}"; do
            echo "123" > "$vimview/$file"
            touch -t 202001011145.14 "$vimview/$file"
          done
          ls "$vimview" && python clean_vimview.py && ls "$vimview"
          unset test_files vimview
