# TODO: READ hyperlink below.
# https://stibel.icu/devops/ci/local-repository.html
name: CI/CD validator designed for init_sh and clean_vimview.py

on: [push]
jobs:
  fetch-assets-testx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        payload: ["3\\n-1\\n1\\n", "3\\n-1\\n2\\n"]
      max-parallel: 2

    steps:
      - name: 切分支
        uses: actions/checkout@main

      - name: 运行 init.sh 并检查是否安装得当
        env:
          payload: ${{ matrix.payload }}
          # 加入重入测试
        run: |
          echo -e "$payload" > tmp_inp.txt
          if [[ ! -s tmp_inp.txt ]]; then
            echo "invalid inp-file size was detected!"
            exit 1
          fi 
          sed -i 's/set -u/set -ux/g' init.sh
          bash init.sh < tmp_inp.txt 
          bash init.sh < tmp_inp.txt && rm tmp_inp.txt
          cur_path=`pwd`
          cd "$HOME/.vim/" && ls autoload colors
          ls "$HOME/.fonts/"
          fc-list | grep -Ei "fira|jetbrain|lxgw" 
          cd "$cur_path" && unset cur_path

  python-remove-test:
    runs-on: ubuntu-latest
    steps:
      - name: 切分支
        uses: actions/checkout@main
        with:
          python-version: "3.12.9"
      - name: 准备测试文件并测试
        run: |
          test_files=(a b c d e f g)
          vimview="$HOME/.vim/view"
          mkdir -p "$vimview" 
          readlink -f "$vimview"
          for file in "${test_files[@]}"; do
            echo "123" > "$vimview/$file"
            touch -t 202001011145 "$vimview/$file"
          done
          ls "$vimview"
          python clean_vimview.py && ls "$vimview" 
          unset test_files vimview
