# TODO: READ hyperlink below.
# https://stibel.icu/devops/ci/local-repository.html
name: init_sh CI/CD

on: [push]
jobs:
  fetch-assets-testx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        payload: ["3\\n-1\\n2\\n", "3\\n-1\\n1\\n"]
      max-parallel: 2

    steps:
      - name: 切分支
        uses: actions/checkout@main

      - name: 安装依赖
        run: sudo apt-get install zsh

      - name: 运行 init.sh 并检查是否安装得当
        env:
          payload: ${{ matrix.payload  }}
        run: |
          echo -e "$payload" > tmp_inp.txt
          if [[ ! -s tmp_inp.txt ]]; then
            echo "invalid inp-file size was detected!"
            exit 1
          fi 
          zsh init.sh < tmp_inp.txt && rm tmp_inp.txt && \
          cd ~/.vim/ && ls autoload colors fonts/*
          determino=(fira jetbrain lxgw)
          for font in "${determino[@]}"; do
            fc-list | grep -i "$font" 
          done

  python-remove-test:
    runs-on: ubuntu-latest
    steps:
      - name: 切分支
        uses: actions/checkout@main
        with:
          python-version: "3.12.9"
      - name: 准备测试文件并测试
        # TODO: 后面应该改成 vimrc 内调用 python 来清理view文件夹下的内容才行
        # cp clean_vimview.py ~/.vim/
        run: |
          test_files=(a b c d e f g)
          vimview="$HOME/.vim/view"
          mkdir -p "$vimview" 
          readlink -f "$vimview"
          for file in "${test_files[@]}"; do
            echo "123" > "$vimview/$file"
            touch -t 202001011145 "$vimview/$file"
          done
          python clean_vimview.py && unset test_files && ls "$vimview" 
          unset vimview
